# File: pyton-test.yml
# Author: Alec Hoelscher with help from Github Copilot
# Date: 03/31/2025
# Description: GitHub Actions workflow to build and test a python app
# This workflow will install Python dependencies and run tests with a single version of Python
# 
# NOTE: Based on GitHub Actions "Python application" template 

name: run-tests
env:
  PYTHON_VERSION: "3.13"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    env:
      PYTHONPATH: "./src"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install -r tests/requirements.txt
          pip install -r ./requirements.txt

      - name: Test with pytest
        run: pytest
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}