[client]
toolbarMode = "minimal"

[logger]
level = "warning"

[theme]
primaryColor="#000000"
backgroundColor="#325ca8"
secondaryBackgroundColor="#91a9ff"
textColor="#dbe3ff"
font="verdana"

[browser]
gatherUsageStats = false